// Bundles each hook entry point into one self-contained .mjs in plugin/dist (Rule A7).
// `node build.mjs --check` rebuilds in memory and fails if plugin/dist is stale.
import { build } from "esbuild";
import { readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outdir = join(here, "..", "..", "plugin", "dist");
const entries = ["session-start", "route", "capture", "session-end"];
const MAX_BYTES = 300 * 1024; // Part L: keep each bundle under 300 KB.
const check = process.argv.includes("--check");

const result = await build({
  entryPoints: entries.map((e) => join(here, "src", `${e}.ts`)),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  outdir,
  outExtension: { ".js": ".mjs" },
  write: false,
  minify: false,
  legalComments: "none",
  banner: { js: "// Generated by packages/hooks/build.mjs. Do not edit." },
  logLevel: "warning",
});

let stale = [];
for (const file of result.outputFiles) {
  const name = file.path.split(/[\\/]/).pop();
  if (file.contents.byteLength > MAX_BYTES) {
    console.error(`${name} is ${file.contents.byteLength} bytes, over the ${MAX_BYTES} byte budget`);
    process.exit(1);
  }
  const text = file.text.replace(/\r\n/g, "\n");
  if (check) {
    const current = existsSync(file.path) ? readFileSync(file.path, "utf8").replace(/\r\n/g, "\n") : null;
    if (current !== text) stale.push(name);
  } else {
    mkdirSync(dirname(file.path), { recursive: true });
    writeFileSync(file.path, text);
  }
}
if (check && stale.length) {
  console.error(`plugin/dist is stale: ${stale.join(", ")}. Run \`npm run build\` in packages/hooks.`);
  process.exit(1);
}
console.log(check ? "plugin/dist is up to date" : `built ${result.outputFiles.length} hooks into plugin/dist`);
