"""Generate TypeScript and Python types from schemas/*.schema.json.

Stdlib only (ADR 0002). Supports the JSON Schema subset the schemas use: object,
array, string, integer, number, boolean, null, enum, const, $ref to local $defs,
and type unions written as a list. Also embeds schemas/redaction-rules.json into
both languages (ADR 0004).

Usage:
    python scripts/codegen.py          write generated files
    python scripts/codegen.py --check  exit 1 if generated files are stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "schemas"
TS_OUT = ROOT / "packages" / "hooks" / "src" / "generated"
PY_OUT = ROOT / "core" / "praxis" / "generated"

HEADER = "Generated by scripts/codegen.py from schemas/. Do not edit by hand."

SCHEMA_FILES = [
    "spool-line.schema.json",
    "snapshot.schema.json",
    "skill-card.schema.json",
    "candidate.schema.json",
    "evidence-manifest.schema.json",
]


def _ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    t = node.get("type", "object")
    if isinstance(t, list):
        return " | ".join(_ts_type({**node, "type": x}) for x in t)
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        inner = _ts_type(node.get("items", {}))
        return f"Array<{inner}>"
    if t == "object":
        if "properties" in node:
            raise ValueError("inline object with properties: move it to $defs")
        return "Record<string, unknown>"
    raise ValueError(f"unsupported type {t!r}")


def _py_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return f"Literal[{node['const']!r}]"
    if "enum" in node:
        return "Literal[" + ", ".join(repr(v) for v in node["enum"]) + "]"
    t = node.get("type", "object")
    if isinstance(t, list):
        return " | ".join(_py_type({**node, "type": x}) for x in t)
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "null":
        return "None"
    if t == "array":
        return f"list[{_py_type(node.get('items', {}))}]"
    if t == "object":
        if "properties" in node:
            raise ValueError("inline object with properties: move it to $defs")
        return "dict[str, Any]"
    raise ValueError(f"unsupported type {t!r}")


def _objects(schema: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    out = [(name, node) for name, node in schema.get("$defs", {}).items()]
    out.append((schema["title"], schema))
    return out


def gen_ts(schemas: list[dict[str, Any]]) -> str:
    lines = [f"// {HEADER}", "/* eslint-disable */", ""]
    for schema in schemas:
        for name, node in _objects(schema):
            if node.get("description"):
                lines.append(f"/** {node['description']} */")
            lines.append(f"export interface {name} {{")
            required = set(node.get("required", []))
            for prop, sub in node.get("properties", {}).items():
                opt = "" if prop in required else "?"
                lines.append(f"  {prop}{opt}: {_ts_type(sub)};")
            lines.append("}")
            lines.append("")
    return "\n".join(lines)


def gen_py(schemas: list[dict[str, Any]]) -> str:
    lines = [
        f'"""{HEADER}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
    ]
    for schema in schemas:
        for name, node in _objects(schema):
            lines.append("")
            lines.append(f"class {name}(TypedDict):")
            if node.get("description"):
                lines.append(f'    """{node["description"]}"""')
                lines.append("")
            required = set(node.get("required", []))
            props = node.get("properties", {})
            if not props:
                lines.append("    pass")
            for prop, sub in props.items():
                t = _py_type(sub)
                if prop not in required:
                    t = f"NotRequired[{t}]"
                lines.append(f"    {prop}: {t}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def gen_rules_ts(rules: dict[str, Any]) -> str:
    body = json.dumps(rules, indent=2, ensure_ascii=False)
    return f"// {HEADER}\n/* eslint-disable */\nexport const REDACTION_RULES = {body} as const;\n"


def gen_rules_py(rules: dict[str, Any]) -> str:
    body = json.dumps(rules, indent=4, ensure_ascii=False)
    return (
        f'"""{HEADER}"""\n\nfrom __future__ import annotations\n\nimport json\nfrom typing import Any\n\n'
        f"REDACTION_RULES: dict[str, Any] = json.loads(\n    r'''{body}'''\n)\n"
    )


def outputs() -> dict[Path, str]:
    schemas = [json.loads((SCHEMAS / f).read_text(encoding="utf-8")) for f in SCHEMA_FILES]
    rules = json.loads((SCHEMAS / "redaction-rules.json").read_text(encoding="utf-8"))
    return {
        TS_OUT / "types.ts": gen_ts(schemas),
        TS_OUT / "redaction-rules.ts": gen_rules_ts(rules),
        PY_OUT / "types.py": gen_py(schemas),
        PY_OUT / "redaction_rules.py": gen_rules_py(rules),
        PY_OUT / "__init__.py": f'"""{HEADER}"""\n',
    }


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if check and stale:
        print("generated files are stale; run `python scripts/codegen.py`:", *stale, sep="\n  ")
        return 1
    if not check:
        print(f"wrote {len(stale)} file(s)" if stale else "generated files up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
